### ISSUE TITLE
Multiple hosts?

### ISSUE THREAD

**Issue by aphilgr1** [matthew-larner/philips-dynalite-mqtt#14]
I have a hotel with 17 rooms, therefore 17 PDEGs and a Supervisor PDDEG. I want to control dynalite with HASS but all solutions seem mediocre, because states do not populate. It seems like one way communication! 

Anyway, I found some workarounds and the question is: Does your integration support multiple gateways? If so, how to configure the yml file?

**Comment by matthew-larner** [comment]
I'll be pushing an update soon that will have it send presets for on/off so Dynalite remembers the states.

Also, yes, the system should support multiple gateways. Just add multiple gateways in the YAML config. If it doesn't, let me know.

**Comment by aphilgr1** [comment]
Hello,

This is good news. For the moment, I have been using cgi commands with preconfigured light scenes but one way communication. it would be nice to eventually be able to control lights directly.

However, on the multiple gateways issue, the problem is that I’m using the same area numbering for each room, and apply offset on the gateway for each corresponding room number. For instance, for room 101 I apply offset of 11000. So area 2 (lights) for room 101 is 11002. Consecutively the same area for room 206 would be 26002. Of course this is handled by the PDDEG supervisor with Dynet 2 protocol while Dynet 1 only supports 0-255. Eventually, no matter how many rooms and how many gateways are used, It is only the last integration that registers area 2. So to my opinion, I believe the only solution would, be either to create entities that will take into consideration the gateway number, or if possible, somehow make use of the offset that is applied by the gateways

**Comment by aphilgr1** [comment]
Just an idea:

In the form where entities are created based on areas and channel numbers, it would be great if we have the option to prepend the last three digits of the gateway's IP address on the entity name. For instance, if we have a gateway with IP XXX.XXX.XXX.206 area 2 on this gateway should be called 206002 and area 255 called 206255. If the IP address is XXX.XXX.XXX.3, then area 2 would be 3002 and area 255 would be 3255.
