### ISSUE TITLE
Motion sensor

### ISSUE THREAD

**Issue by Lialeli** [matthew-larner/philips-dynalite-mqtt#7]
Hello! Thanks for your work. I use your program and receive data from the light, but I do not receive data from motion sensors. Could you suggest what could be the reason? Motion sensors Philips Dynalite DUS360CR-D. And I am using code like this.
dynalite:
   bridges:
     - host: 10.10.10.10
       port: 50000
       area:
         "81":
           name: Test
           channel:
             "32":
               name: Motion_test
               type: motion

**Comment by matthew-larner** [comment]
ah yes, this requires a special setup. I'll add it to the readme.md file now.
